### ISSUE TITLE
Migliorare design su mobile

### ISSUE THREAD

**Issue by elmazzun** [visiont3lab/covid19-dash-plotly#1]
Quando si clicca su una figura, zooma automaticamente.

**Comment by visiont3lab** [comment]
Problema:

Possibili soluzioni:

Ci sono dei parametri di configurazione dello zoom in [dcc.graph component (scrollZoom](https://dash.plotly.com/dash-core-components/graph) ma non disabilita lo zoom sugli assi.
Una possibile soluzione è usare  il parametro [fixedrange](https://plotly.com/python/reference/) nel layout di ogni figura
* xasis = dict(fixedrange=True)
* yasis = dict(fixedrange=True)
Che disabilita lo scaling degli assi in una drizione

Inoltre è possibile selezionare il pan invece che lo zoom nella modebar. [How to select pan as default tool](https://community.plotly.com/t/how-to-select-pan-as-default-tool/3152)
Bisogna guardare il parametro in [ figure reference ](https://plotly.com/python/reference/#layout-dragmode ) **dragmode**

Potrebbe essere interessante capire come distingure una request che viene dal telefono da una dal browser. Bisognerebbe cercare qualcosa su flask (se non si trova nulla su dash)  in quanto dash semplicemente estende le funzioni di flask.


RIsolto

Commit:
Bug: Migliorare design su Mobile, Aggiunto fixed range (see Figure reference plotly , dragmode, fixedrange) per evitare che vi sia un movimento della figura verso l'alto
676801c2c07dc892a01b857e29dda91fec22b81c
