### ISSUE TITLE
Quale SW di collaborazione usare?

### ISSUE THREAD

**Issue by elmazzun** [visiont3lab/covid19-dash-plotly#18]
In parole povere: dove chattiamo per discutere robe?
Sarebbe preferibile non intasare la sezione [Issues](https://github.com/visiont3lab/covid19-dash-plotly/issues) con discussioni su dettagli implementativi.
Possibili SW di collaborazione sarebbero:

- Telegram (magari in gruppo apposito, non il solito _t3club_);
- Rocket.chat;
- Gitter;
- ... (eventuali vostre proposte);

Finche' si tratta di scambiarci semplici messaggi di testo e non dobbiamo collegare alle conversazioni oggetti piu' complessi di un link, tutte le altre applicazioni mi sembrano un overkill e credo che un apposito gruppo Telegram sia piu' che sufficiente.

**Comment by visiont3lab** [comment]
Andiamo con slack e vediamo come va
